In [1]:
import pandas as pd

In [2]:
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

In [3]:
url = URL.create(
    drivername="postgresql+psycopg2",
    username="postgres",
    password="Sql2701",
    host="localhost",
    port=5432,
    database="superstore_db"
)

engine = create_engine(url)

print("Connection Successful!")

Connection Successful!

In [4]:
query = 'SELECT * FROM superstore'

df = pd.read_sql(query, engine)

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960
1,2,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",500.108
2,3,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620
3,4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,500.108
4,5,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368

In [5]:
query = """
SELECT "Product Name",
       SUM("Sales") AS Total_Sales
FROM superstore
GROUP BY "Product Name"
ORDER BY Total_Sales DESC
LIMIT 5;
"""

top_products = pd.read_sql(query, engine)

top_products

                                        Product Name  total_sales
0                           SAFCO Arco Folding Chair     6050.640
1                        Tennsco Double-Tier Lockers     5631.136
2         Bretford Rectangular Conference Table Tops     5602.888
3  Hon Deluxe Fabric Upholstered Stacking Chairs,...     5550.086
4         GBC DocuBind TL300 Electric Binding System     5501.188

In [6]:
query = """
SELECT "Category",
SUM("Sales") AS Total_Sales

FROM superstore

GROUP BY "Category"

ORDER BY Total_Sales DESC;
"""

category_sales = pd.read_sql(query, engine)

category_sales

          Category  total_sales
0  Office Supplies  482907.7900
1        Furniture  471919.6588
2       Technology  421649.6190

In [7]:
query = """
SELECT "Region",
SUM("Sales") AS Total_Sales

FROM superstore

GROUP BY "Region"

ORDER BY Total_Sales DESC;
"""

region_sales = pd.read_sql(query, engine)

region_sales

    Region  total_sales
0     West  453716.8785
1     East  389979.4440
2  Central  306734.7198
3    South  226046.0255

In [8]:
query = """
SELECT "Customer Name",
SUM("Sales") AS Total_Sales

FROM superstore

GROUP BY "Customer Name"

ORDER BY Total_Sales DESC

LIMIT 10;
"""

customers = pd.read_sql(query, engine)

customers

     Customer Name  total_sales
0      Clay Ludtke     5801.690
1      Seth Vernon     5782.619
2  Laura Armstrong     5252.122
3       Paul Prost     5197.144
4       Brian Moss     5137.571
5  Dan Reichenbach     5120.388
6         John Lee     5115.204
7    William Brown     5102.014
8    Maria Etezadi     5043.836
9     Ken Lonsdale     4872.015

In [9]:
query = """
SELECT "State",
SUM("Sales") AS Total_Sales

FROM superstore

GROUP BY "State"

ORDER BY Total_Sales DESC;
"""

states = pd.read_sql(query, engine)

states

                   State  total_sales
0             California  286331.0655
1               New York  166127.1210
2                  Texas  115095.4628
3             Washington   75211.9600
4           Pennsylvania   74899.7350
5               Illinois   59396.5350
6                   Ohio   53615.7900
7                Florida   47076.6375
8               Michigan   42607.2080
9               Virginia   36151.8700
10        North Carolina   31567.7670
11               Arizona   28937.5330
12               Georgia   27285.7100
13              Colorado   23940.1110
14              Kentucky   22663.9720
15               Indiana   21688.3680
16         Massachusetts   20566.1880
17             Tennessee   20363.9950
18             Wisconsin   19614.8520
19            New Jersey   16750.2280
20              Maryland   16059.2760
21                Oregon   15134.8350
22             Minnesota   13653.2700
23              Delaware   12940.8350
24              Oklahoma   12618.0780
25               Alabama   10907.4460
26           Connecticut   10888.1990
27          Rhode Island   10114.1760
28              Missouri    9930.5200
29              Arkansas    8798.9860
30           Mississippi    8198.8280
31                  Utah    6973.8240
32             Louisiana    6560.9860
33        South Carolina    6469.8280
34                Nevada    6406.7960
35         New Hampshire    4492.9920
36              Nebraska    4334.3420
37            New Mexico    4259.1560
38                 Idaho    3557.8920
39                Kansas    2914.3100
40                  Iowa    2850.9560
41               Montana    2463.5980
42          South Dakota    1315.5600
43                 Maine    1270.5300
44  District of Columbia    1217.7860
45         West Virginia    1036.5880
46          North Dakota     715.2580
47               Wyoming     500.1080

In [10]:
query = """
SELECT "Sub-Category",
SUM("Sales") AS Total_Sales

FROM superstore

GROUP BY "Sub-Category"

ORDER BY Total_Sales DESC;
"""

subcategory = pd.read_sql(query, engine)

subcategory

   Sub-Category  total_sales
0        Phones  219882.4460
1        Chairs  202068.2750
2       Storage  162170.2800
3   Accessories  124429.0580
4        Tables  116591.4835
5       Binders   98460.6070
6   Furnishings   82583.7460
7         Paper   76115.2860
8    Appliances   73226.4530
9     Bookcases   70676.1543
10     Machines   44972.3370
11      Copiers   32365.7780
12          Art   26084.4540
13    Envelopes   16021.4580
14     Supplies   15895.0140
15       Labels   11932.2780
16    Fasteners    3001.9600

In [11]:
query = """
SELECT "City",

SUM("Sales") AS Total_Sales

FROM superstore

GROUP BY "City"

ORDER BY Total_Sales DESC

LIMIT 10;
"""

cities = pd.read_sql(query, engine)

cities

            City  total_sales
0  New York City  135676.6530
1    Los Angeles  112134.4785
2   Philadelphia   68873.1280
3  San Francisco   65388.0680
4        Seattle   63287.3440
5        Houston   43781.5296
6        Chicago   33998.6130
7      San Diego   29447.6080
8       Columbus   28798.7910
9    Springfield   23003.3540

In [12]:
from db_utils import run_query

query = """
SELECT *
FROM superstore
LIMIT 5;
"""

df = run_query(query)
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960
1,2,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",500.108
2,3,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620
3,4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,500.108
4,5,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368